on:
  workflow_dispatch:
  push:
    branches: main
  pull_request:
    branches: main
    
  schedule:
    - cron: "0 08 * * *"

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install TinyTeX
        run: |
          curl -fsSL https://yihui.org/tinytex/install-unx.sh | sh -s - --admin
          echo "export PATH=$HOME/.TinyTeX/bin/x86_64-linux:$PATH" >> $GITHUB_ENV
          echo "TEXINPUTS=.:$TEXINPUTS" >> $GITHUB_ENV
          echo "TEXMFHOME=$HOME/texmf" >> $GITHUB_ENV
          source $GITHUB_ENV
          ~/.TinyTeX/bin/x86_64-linux/tlmgr update --self --all
          ~/.TinyTeX/bin/x86_64-linux/tlmgr install \
            koma-script \
            xetex \
            fontspec \
            babel \
            times \
            graphics \
            grfext \
            fancyhdr \
            longtable
          
      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html 

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
